POST http://localhost:8000/posts
Content-Type: application/json

{
  "title": "title08",
  "content": "content",
  "author":"seha"
}

###
GET http://localhost:8000/posts?limit=a

###
GET http://localhost:8000/posts/6785f901403a9f1cfb14b5ba